# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-28 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('cureDuration', models.CharField(max_length=50, verbose_name='\u65f6\u957f')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2016, 8, 28, 15, 22, 28, 348266, tzinfo=utc), verbose_name='\u65e5\u671f')),
                ('note', models.CharField(default='', max_length=200, verbose_name='\u5907\u6ce8')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
                ('operator', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u8005')),
                ('status', models.IntegerField(verbose_name='\u72b6\u6001')),
            ],
        ),
    ]
