# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.IntegerField()),
                ('key_from', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lentype_all', models.BooleanField()),
                ('lentype_0_10', models.BooleanField()),
                ('lentype_10_30', models.BooleanField()),
                ('lentype_30_60', models.BooleanField()),
                ('lentype_60_More', models.BooleanField()),
                ('operation_date', models.DateTimeField()),
                ('platform_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosearch.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_include', models.CharField(max_length=100)),
                ('key_exclude', models.CharField(max_length=100)),
                ('platform_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosearch.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(verbose_name='create time')),
                ('video_platforms', models.CharField(max_length=300)),
                ('configs', models.TextField()),
            ],
        ),
    ]
