# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videosearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 8, 56, 1, 348436, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 8, 56, 1, 348977, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 8, 56, 1, 350396, tzinfo=utc), verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
    ]
