# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='site',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
