# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videosearch', '0002_platform_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='lentype_0_10',
            field=models.BooleanField(verbose_name='0-10\u5206\u949f'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='lentype_10_30',
            field=models.BooleanField(verbose_name='10-30\u5206\u949f'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='lentype_30_60',
            field=models.BooleanField(verbose_name='30-60\u5206\u949f'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='lentype_60_More',
            field=models.BooleanField(verbose_name='60\u5206\u949f\u4ee5\u4e0a'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='lentype_all',
            field=models.BooleanField(default=True, verbose_name='\u5168\u90e8'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 9, 18, 31, 722576, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='platformkeys',
            name='key_exclude',
            field=models.CharField(max_length=100, verbose_name='\u6392\u9664\u5173\u952e\u8bcd'),
        ),
        migrations.AlterField(
            model_name='platformkeys',
            name='key_include',
            field=models.CharField(max_length=100, verbose_name='\u5305\u542b\u5173\u952e\u8bcd'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 9, 18, 31, 723947, tzinfo=utc), verbose_name='create time'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='video_platforms',
        ),
        migrations.AddField(
            model_name='task',
            name='video_platforms',
            field=models.ManyToManyField(to='videosearch.Platform'),
        ),
    ]
