# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videosearch', '0003_auto_20160508_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformconfig',
            old_name='platform_name',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='platformkeys',
            old_name='platform_name',
            new_name='platform',
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 14, 30, 19, 531376, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 14, 30, 19, 532510, tzinfo=utc), verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u540d\u79f0'),
        ),
    ]
