# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videosearch', '0004_auto_20160508_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 15, 30, 30, 827165, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='key_from',
            field=models.IntegerField(verbose_name='\u5173\u952e\u8bcd\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='page_count',
            field=models.IntegerField(verbose_name='\u641c\u7d22\u9875\u6570'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 15, 30, 30, 827844, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 15, 30, 30, 829144, tzinfo=utc), verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
    ]
