# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videosearch', '0006_auto_20160514_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 13, 27, 24, 222943, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='operation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 13, 27, 24, 223426, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='configs',
        ),
        migrations.AddField(
            model_name='task',
            name='configs',
            field=models.TextField(default='', verbose_name='\u914d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 13, 27, 24, 224694, tzinfo=utc), verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='video_platforms',
        ),
        migrations.AddField(
            model_name='task',
            name='video_platforms',
            field=models.CharField(default='', max_length=200, verbose_name='\u5e73\u53f0'),
        ),
    ]
